export const ActionTypes = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  SET_CATEGORIES: 'SET_CATEGORIES',
  ADD_TO_CART:'ADD_TO_CART'
};
